### ISSUE TITLE
Automatic Installation  ` react native link `  include RNMailTests.xctest 

### ISSUE THREAD

**Issue by konchanSS** [chirag04/react-native-mail#101]
Hello, I'm very grateful that I usually use react-native-mail to create my app .

However,  Automatic Installation include RNMailTests.xctest in Linked framework and Libraries.
![image](https://user-images.githubusercontent.com/13659262/37518572-0c458c88-2959-11e8-9c9d-fefa1913315a.png)

this causes debug error on actual device . 

![image](https://user-images.githubusercontent.com/13659262/37518693-9005630e-2959-11e8-98b8-13109aca67a8.png)

is RNMailTests.xctest need in Linked framework and Libraries ?

**Comment by chirag04** [comment]
Feel free to send a PR. i would recommend just removing RNMailTests.

**Comment by Suraj-Tiwari** [comment]
This pr merge is released on npm? my build contains RNMailTests 😕
