### ISSUE TITLE
RNMailTests requires a development team

### ISSUE THREAD

**Issue by elmbrent** [chirag04/react-native-mail#131]
When installed and run in Xcode I am prompt with the following : 

> :-1: Signing for "RNMailTests" requires a development team. Select a development team in the project editor. (in target 'RNMailTests')

I have tried adding to schema but I don't see any were I can add my development team to RNMail? Can anyone advise please.

**Comment by elmbrent** [comment]
Had to install manually.

**Comment by spacewaffle** [comment]
Still having an issue here. I went through all the manual ios steps. RNMail.xcodeproj is in my libraries, libRNMail.a is setup in Build phases > Link Binary with Libraries. I even changed the way I imported it. No dice.

**Comment by spacewaffle** [comment]
Nevermind. Removing RNMailTests from Build Phases > Link Binary with Libraries did the trick.
