### ISSUE TITLE
Way to know if email was actually sent or cancelled?

### ISSUE THREAD

**Issue by krstffr** [chirag04/react-native-mail#149]
In the New email-overlay the user can either choose to tap the Send button to send the email, or tap the Cancel button to cancel sending the email. Right now (as far as I am concerened) there is no way to know in the mail() callback if the user clicked Send or Cancel?

This feature would be great as an app might need to know if the user actually attempted to send an email or not.

**Comment by frederic33** [comment]
I don't found a way to do this with "flutter_mailer" package for example. The 'send' function is a Future<void> so that doesn't provide any feedback. A Future<bool> should be a good way to know.

**Comment by Relax594** [comment]
on iOS this is possible. You can listen on that "event" flag in the callback.

```
 Mailer.mail(
        {
            subject: 'Hey',
            body: 'This is cool.',
        },
        (error, event) => {
            if (event === 'sent') {
                // do something..
            } else if (event === 'cancelled') {
                // user cancelled
            }
        }
```

**Comment by chirag04** [comment]
On android it's not possible because android doesn't provide any hook for sent or canceled. on ios it should work the way @Relax594 mentioned.
