### ISSUE TITLE
5.0.0 crash in android

### ISSUE THREAD

**Issue by jihokim2** [chirag04/react-native-mail#151]
I can not build in android.

Log is like this.

/react-native-mail/android/src/main/java/com/chirag/RNMail/RNMailModule.java:90: error: cannot find symbol
       ArrayList<Uri> uris = new ArrayList<Uri>();
       ^
  symbol:   class ArrayList
  location: class RNMailModule
/react-native-mail/android/src/main/java/com/chirag/RNMail/RNMailModule.java:90: error: cannot find symbol
       ArrayList<Uri> uris = new ArrayList<Uri>();
                                 ^
  symbol:   class ArrayList
  location: class RNMailModule
Note: /node_modules/react-native-mail/android/src/main/java/com/chirag/RNMail/RNMailModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

Please, fix this.

**Comment by Relax594** [comment]
+1

**Comment by chirag04** [comment]
@brightsider looks like an import issue. can somebody send a PR real quick?

**Comment by Relax594** [comment]
https://github.com/chirag04/react-native-mail/pull/152

**Comment by chirag04** [comment]
awesome! thank you. published 5.0.1 with the fix,.
