### ISSUE TITLE
After Recent Multiple Attachment Update No Files Attach

### ISSUE THREAD

**Issue by systemlevel** [chirag04/react-native-mail#153]
Pulled down the recent master updates featuring the updated multiple attachment support. However I cannot get any attachments to work. Here's my config:

```
		Mailer.mail(
			{
				subject: 'Document',
				recipients: [ 'office@company.com' ],
				body: '<b>Document attached:</b>',
				isHTML: true,
				attachments: [
					{
						path: attachmentPathCsv,
						type: 'csv' // Mime Type: jpg, png, doc, ppt, html, pdf, csv
					},
					{	
						path: attachmentPath,
						type: 'pdf'
					}
				]
			},
			(error, event) => {
				Alert.alert(
					error,
					event,
					[
						{ text: 'Ok', onPress: () => console.log('OK: Email Error Response') },
						{ text: 'Cancel', onPress: () => console.log('CANCEL: Email Error Response') }
					],
					{ cancelable: true }
				);
			}
		);
```

**Comment by chirag04** [comment]
is the attachment path correct?

**Comment by systemlevel** [comment]
Yes, it works on iOS just fine.  Both get attached.  Android is the issue.  Not working in Android simulator or on actual Android device.  

See anything wrong with my approach?

**Comment by Relax594** [comment]
Same issue here. Just one attachment should get attached but it's not showing up in mail.

**Comment by Relax594** [comment]
@chirag04 any progress on this one? Android Mail is useless in its current state.

**Comment by orengatigno** [comment]
Same issue here.

The 'react-native-mail' does not work with attachment files after upgrading to version @5.0.1.
I worked with version @4.1.0 with a single attachment and it works fine, but with @5.0.1 I changed the var to attachment -> attachments and changed it to the array, and it stopped to attach the file.


```
//1 attachment work react-native-mail version 4.1.0 attachment work
mailOptions.attachment = { path: androidLogConcatTxtFilePath, type: 'doc' };
//array attachments not work react-native-mail version 5.0.1  not work
mailOptions.attachments = [{ path: androidLogConcatTxtFilePath, type: 'doc' }];
```

**Comment by grit96** [comment]
I experienced this issue in tandem with #123 

I've worked around both of them using [this](https://gist.github.com/grit96/3ec60fd657af831c8a5c61f9dd78c43a) `patch-package` fix.

The caveat is that it will only use the last attachment of the `attachments` array.

**Comment by chirag04** [comment]
@grit96 can you send a PR that works for all attachments?

**Comment by grit96** [comment]
I've updated my [patch](https://gist.github.com/grit96/3ec60fd657af831c8a5c61f9dd78c43a) to use `Intent.ACTION_SEND_MULTIPLE` which allows multiple attachments to work properly, but it shows more apps in the chooser than just email clients like it did with `Intent.ACTION_SENDTO`.

I haven't found a working fix for this but I can make a PR with this patch if you want?

**Comment by Relax594** [comment]
Any solution? Otherwise please revert the update for Android..

**Comment by Relax594** [comment]
sadly no.

**Comment by cristianoccazinsp** [comment]
Tried an older version as well, looks like it is full of bugs and can't be used with up-to-date react native versions.  I wonder if there are any alternatives.

**Comment by Relax594** [comment]
AFAIK there are not that many bugs in the latest 4.x. Sadly i haven't found any alternatives which support attachments..

**Comment by chirag04** [comment]
Happy to accept a PR for multiple attachments. Sorry, haven't had time to actively work on this.

**Comment by grit96** [comment]
I don't have time to create a PR currently but someone is welcome to convert my `patch-package` [patch](https://gist.github.com/grit96/3ec60fd657af831c8a5c61f9dd78c43a) into a PR.
