### ISSUE TITLE
Multiple file attachments not working

### ISSUE THREAD

**Issue by sankar9659** [chirag04/react-native-mail#167]
Multiple file attachment not working for both android and ios, any solution for this issue?

my code is:

          `Mailer.mail({
                subject: 'Artwork Details',
                recipients: ['support@example.com'],
                ccRecipients: ['supportCC@example.com'],
                bccRecipients: ['supportBCC@example.com'],
                body: `${artwrks.title}`,
                customChooserTitle: "This is my new title", // Android only (defaults to "Send Mail")
                isHTML: true,
                attachments: [{
                    path: '/data/user/0/com.galleryassistant/cache/11025/image_1611136953276',
                    type: 'jpg', 
                   path: '/data/user/0/com.galleryassistant/cache/11025/image_1611136953276',
                    type: 'jpg',
                }],
            }, (error, event) => {
                Alert.alert(
                    error,
                    event,
                    [
                        { text: 'Ok', onPress: () => console.log('OK: Email Error Response') },
                        { text: 'Cancel', onPress: () => console.log('CANCEL: Email Error Response') }
                    ],
                    { cancelable: true }
                )
            });`

Thanks in advance.

**Comment by scblason** [comment]
It seems that the attachments are not properly defined, should be: 

`
Mailer.mail({
            subject: 'Artwork Details',
            recipients: ['support@example.com'],
            ccRecipients: ['supportCC@example.com'],
            bccRecipients: ['supportBCC@example.com'],
            body: `${artwrks.title}`,
            customChooserTitle: "This is my new title", // Android only (defaults to "Send Mail")
            isHTML: true,
            attachments: [{
                 path: '/data/user/0/com.galleryassistant/cache/11025/image_1611136953276',
                 type: 'jpg', 
                }
               { 
                path: '/data/user/0/com.galleryassistant/cache/11025/image_1611136953276',
                type: 'jpg',
            }],
        }, (error, event) => {
            Alert.alert(
                error,
                event,
                [
                    { text: 'Ok', onPress: () => console.log('OK: Email Error Response') },
                    { text: 'Cancel', onPress: () => console.log('CANCEL: Email Error Response') }
                ],
                { cancelable: true }
            )
        });
`
