### ISSUE TITLE
Mail Window Opens and Closes

### ISSUE THREAD

**Issue by bendellarocco** [chirag04/react-native-mail#17]
viewServiceDidTerminateWithError: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 "(null)" UserInfo={Message=Service Connection Interrupted}

**Comment by chirag04** [comment]
is it in the simulator? I have seen it crash on the simulator but works fine on real device.

**Comment by bendellarocco** [comment]
Yes it's only simulator. I tested on a real device later and it was fine.

**Comment by ararog** [comment]
I'm getting the window opening and closing followed by a crash on similator

**Comment by bendellarocco** [comment]
I got the same issue. Load it on an actual device and it works fine.

**Comment by bhumit1709** [comment]
This is not an issue. MailController works only with device , it crashes on simulator even when using native Objective C project, so this can be ignored.
