### ISSUE TITLE
Add 'Email' to description for SEO

### ISSUE THREAD

**Issue by AdamBrodzinski** [chirag04/react-native-mail#2]
I almost missed this module because I was searching for react-native email on Google, Github, and React Parts. I ended up bumping into it via http://www.reactnative.com/keep-your-contacts-closer-with-react-native/

If you would add the keyword Email to the repo desc and/or the Readme it might help rank. I like this module because it's not a kitchen sink like 'react-native-communications' is. 

Thanks! :beers:

**Comment by chirag04** [comment]
want to PR? Thanks for the suggestion.

**Comment by chirag04** [comment]
I think it's there now.
