### ISSUE TITLE
Can't Find libRNMail.a in Xcode > Libraries

### ISSUE THREAD

**Issue by jeremypagley** [chirag04/react-native-mail#23]
Everything with android worked just fine but as you can see in the image below I cant seem to find the `libRNMail.a` library?

<img width="406" alt="screen shot 2016-05-20 at 11 24 38 am" src="https://cloud.githubusercontent.com/assets/5873346/15432742/80fcd25e-1e7d-11e6-9d4d-5c6d71ebc4c4.png">

**Comment by chirag04** [comment]
did you add it in your xcode project correctly?

**Comment by jeremypagley** [comment]
@chirag04 I just did an npm install, and the next step after that is to add that library but it cant find it? Any thoughts?

**Comment by chirag04** [comment]
npm install and next step is to add it to your xcode project. click your xcode project -> libraries -> add files -> goto node_modules/react-native-mail/RNMail.xcodeproj.

after that you goto xcode project -> build phases -> libraries -> add librnmail

**Comment by jeremypagley** [comment]
Yes sir, I already tried that as you can see In the image above. Xcode
can't fine that library is there another way to get it?

**Comment by jeremypagley** [comment]
@chirag04 Thank you very much that fixed the issue!! Thanks for building his awesome library its a life savor
