### ISSUE TITLE
[Question] How should the absolute path look like?

### ISSUE THREAD

**Issue by mayzhao3131** [chirag04/react-native-mail#26]
I am not sure if this is the correct place to ask this question but I am unable to find any other place that discusses react-native-mail. 
I tried using the example code provided in my app, but got the error 
"Exception '-[MFMailComposeInternalViewController addAttachmentData:mimeType:fileName:] attachment must not be nil.' was thrown while invoking mail on target RNMail with params (
        {
        attachment =         {
            name = default;
            path = "./res/default.png";
            type = png;
        };
        body = "";
        isHTML = 1;
        recipients =         (
            "test@test.com"
        );
        subject = "Test Subject";
    },
    265
)"

My code is provided below. If I comment out the attachment part, the email pops up as expected with subject and recipients fields filled out. I wonder if there is a problem with how I enter the path. I've also tried 'projName/js/res/default.png' but that did not work out either. The file is at the correct location as I am using the same picture somewhere else in the class by calling require('./res/default.png)' and that picture loads. 
Any help would be appreciated. Thank you.
  sendEmail: function() {
    Mailer.mail({
      subject: 'Test Subject',
      recipients: 'test@test.com',
      body: '',
      isHTML: true,
      attachment: {
        path: './res/default.png',
        type: 'png',
        name: 'default',
      }
    }, (error, event) => {
        if(error) {
          AlertIOS.alert('Error', 'Could not send mail.');
        }
    });
  },

**Comment by ihor** [comment]
So what is the answer?

**Comment by elmbrent** [comment]
Still no answer? I tried using a web path and it did not work..
