### ISSUE TITLE
update doc for android

### ISSUE THREAD

**Issue by dcz-switcher** [chirag04/react-native-mail#35]
Hello,

Thanks to share your work.
I use react-native 0.32 and there is no onCreate() method in mainActivity.java

To add a package, you have to declare it in method getPackages() of the MainApplication.java and of course import the module in it (and not in mainActivity.java)

Do you wan't I make a pull request ?

regards

**Comment by chirag04** [comment]
sure. Can you send a pull request?

**Comment by JonasWho** [comment]
I cannot get the install to work on Android, can you share the changes that I need to add to MainApplication.java? (in RN 0.31+)

**Comment by dcz-switcher** [comment]
done

note : this is my first pull request on github ;-)
