### ISSUE TITLE
send mail

### ISSUE THREAD

**Issue by eangfmbs** [chirag04/react-native-mail#39]
send mail doesnt work in react native

**Comment by chirag04** [comment]
can you share more info about the error?

**Comment by prabhaav** [comment]
RN: 0.36
iOS 10

The console.log(error) I am seeing is:

> not_available

**Comment by prabhaav** [comment]
@chirag04 any ideas on if this will be fixed for iOS 10?

**Comment by chirag04** [comment]
I can look at it over the weekend. Can you confirm if this works on actual device?

There is an issue with simulator but works fine on device.

**Comment by prabhaav** [comment]
@chirag04 thanks!. Yes the issue happens on device, I am trying it on a iphone 7 and iphone 6.

**Comment by chirag04** [comment]
ok. Thanks for confirming. One more thing, on your device you have the mail app setup with an email account?

**Comment by prabhaav** [comment]
I think that maybe the issue...my native mail app has been acting up. Can someone else confirm on device? If not, i'll try it on another device when I get a chance

**Comment by chirag04** [comment]
for rn-mail to work, the native mail app needs to be configurated. `not_available` is exactly for you to handle it gracefully when the native mail app is not configured.

**Comment by alexszilagyi** [comment]
@chirag04 : then you could we include this in README (documentation file) ? It was confusing for me though. I'd add a PR later for this if you don't mind ;)

**Comment by chirag04** [comment]
Feel free to send a pr
