### ISSUE TITLE
Callback not being called on success on Android

### ISSUE THREAD

**Issue by chetstone** [chirag04/react-native-mail#44]
When running on a simulator I get a callback saying the service is not available.

On a device, the service is available and the mail is sent successfully but the callback is not called at all. Is this expected? The readme says:

> On android callback will only have error(if any) as the argument. event is not available on android.

To me this means the callback should get fired on success, but the error argument will be false or undefined. 

I need to do some bookkeeping after the mail is sent so need to know ...

**Comment by chirag04** [comment]
yes we are not calling the callback after mail is sent on android.

We can call the callback after this line tho: https://github.com/chirag04/react-native-mail/blob/master/android/src/main/java/com/chirag/RNMail/RNMailModule.java#L115

Can you PR?

**Comment by chetstone** [comment]
Thanks a lot for the quick reply. I tried invoking the callback there but it's not really satisfactory. 

In my iOS app when I get the callback I pop up an alert asking the user about the bookkeeping. But in this case the alert gets clobbered by the activity chooser coming up at the same time. 

We really should wait till the activity is done before invoking the callback. Besides, we need to know if the activity was completed or cancelled by the user. 

I'll try to implement an activity result listener. If it works, I'll send a PR.

**Comment by chetstone** [comment]
Well this was my first attempt at android programming and it took me a while but I was able to get an  
onActivityResult callback. Alas, since Android doesn't 'intend' to produce a result from the SEND_TO `intent`, the callback comes back immediately (always with a result of "cancelled"), it doesn't wait till the activity is done. So there's no advantage...

I think what I'll do as a workaround is pop up a reminder for the user to do the bookkeeping manually, with a button for them to press to launch the activity.

I suppose one could listen to `AppState` and do something when the app becomes active again, but that could get really complicated. And even then, you wouldn't know whether the mailing operation was completed or cancelled.
