### ISSUE TITLE
[iOS issue] Argument 1 (RCTResponseSenderBlock) of RNMail must not be null

### ISSUE THREAD

**Issue by kashani** [chirag04/react-native-mail#46]
Hi there,

This is working great on Android, but can't get it to work on iOS. Screenshot and system info below:

- iOS 10.2 (simulator) and iOS 9.3.4 (physical device)
- react: ~15.4.1
- react-native: 0.39.2
- react-native-mail: ^2.0.0

![photo jan 03 2 16 12 pm](https://cloud.githubusercontent.com/assets/8785939/21625301/df6344b8-d1bf-11e6-8862-8d7182208228.png)

**Comment by chirag04** [comment]
are you passing the callback correctly?

**Comment by kashani** [comment]
That was the issue indeed. Kind of obvious, sorry! 
It might be helpful to mention the callback is required on iOS. On Android it's ok to leave it as null.

Thanks for the quick response @chirag04!
