### ISSUE TITLE
Mailer is undefined (Cannot read property 'mail' of undefined.)

### ISSUE THREAD

**Issue by steveleec** [chirag04/react-native-mail#5]
After I did Mailer.mail({..., I got from the console that Cannot read property 'mail' of undefined.

I have defined var Mailer = require('NativeModules').RNMail; at the top the file.

Why is that happening? How can I fix it?

By the way, in your tutorial you say Add the file "libRNMail.a" to Build Phases > Link... However, I couldn't find that file. I found the one being shown in the picture and is "libRNOverlay,a". Is that what you meant? Thanks!

**Comment by steveleec** [comment]
I just fixed.
In your step number 2 you say
"Open your project in XCode, right click on Libraries and click Add Files to "Your Project Name" (Screenshot) then (Screenshot)."
However, the screen shots point to a different library called Overlay. They are the wrong picture.
Not a big deal to fix but that issue could mislead people.

**Comment by chirag04** [comment]
I will try to update the screenshot. closing for now.
