### ISSUE TITLE
Android: event after email sent is not fired

### ISSUE THREAD

**Issue by zizizi17** [chirag04/react-native-mail#58]
Hello.
I have an issue that the event after the letter is sent is not fired. So i cannot handle some actions. Can you recommend something?

**Comment by joonhocho** [comment]
@zizizi17 I've looked at the code and it does not fire sent event.

**Comment by trcarlocastro** [comment]
@joonhocho Do you have any work around for this issue? we also need that event to handle some actions.

**Comment by DanielBoening** [comment]
any update on this issue? Is there a workaround?

**Comment by chirag04** [comment]
duplicate https://github.com/chirag04/react-native-mail/issues/57.

On android, you can listen for app background and active events to know if the user tried to send the event. Note: this will not tell you if the email was actually sent.
