### ISSUE TITLE
Feature: Just open the mail app

### ISSUE THREAD

**Issue by dwilt** [chirag04/react-native-mail#59]
I'm sure this is dead simple but can we have a method (maybe named `open`) that just launches the user's mail application but doesn't compose a message?

**Comment by chirag04** [comment]
use `Linking` module from react native for that.

**Comment by dwilt** [comment]
@chirag04 I can't find an example of this anywhere using `Linking`. Do you have one?

**Comment by chirag04** [comment]
http://facebook.github.io/react-native/releases/0.42/docs/linking.html#openurl

**Comment by dwilt** [comment]
Right, but do you know the value that should be passed in to `openURL` to open the Mail app?

**Comment by dwilt** [comment]
I'm looking into this more and seeing the idea here. We're supposed to pass the URL scheme for iOS or the intent URL for Android. However, this adds lots of extra code:

```
if (Platform.OS === `ios`) {
        const inbox = await Linking.canOpenURL(INBOX_URL_SCHEME);

        if (inbox) {
            Linking.openURL(INBOX_URL_SCHEME);
        } else {
            Linking.openURL(iOS_MAIL_URL_SCHEME);
        }
    } else if (Platform.OS === `android`) {
        const inbox = await Linking.canOpenURL(INBOX_URL_SCHEME);
        const gmail = await Linking.canOpenURL(`com.google.android.gm`);

        if (inbox) {
            Linking.openURL(INBOX_URL_SCHEME);
        } else if (gmail) {
            Linking.openURL(`com.google.android.gm`);
        }
```
And should probably be just handled by this plugin no? It would probably be a lot simpler. Finding examples like this for Android: http://stackoverflow.com/a/31594815/1681896

Since iOS does always default to it's own apps, we could use an android specific method like `openDefaultMailClient` and then for iOS the user could detect which apps are installed like I did above.

**Comment by dwilt** [comment]
For the record, as I mentioned above, the iOS conditional I have works perfect. However, besides `mailto:` (which opens a new message and that's the opposite of this feature request), I can't figure out a value to pass into `openURL` that will launch any kind of mail application on my Android device. I've tried `com.google.android.gm` per http://stackoverflow.com/a/3592060/1681896

**Comment by jasan-s** [comment]
@dwilt  did you find a solution to opening the mail app? I want to launch mail app to guide user to verify email upon account creation.

**Comment by jasan-s** [comment]
I also posted a [stackoverflow ](https://stackoverflow.com/questions/44594818/launch-and-open-email-client-react-native)question:

**Comment by dwilt** [comment]
@jasan-s no, I wasn't able to find one. We ended up abandoning the idea of opening the mail client automatically since the email notification coming in from the top added to the user experience of them seeing the email come in just as we showed the success message of saying we sent one.

**Comment by jasan-s** [comment]
I think I may do the same.

**Comment by markokostovski** [comment]
Would like to say that Linking.openURL('mailto:somethingemail@gmail.com?subject=abcdefg&body=body') worked for me, but only on iOS, when I was on simulator it didn't.. threw error

**Comment by voidstarfire** [comment]
For anyone else stuck on this, you'll have to write a native module as such:

```
public class NativeModuleSendEmail extends ReactContextBaseJavaModule {

    public NativeModuleSendEmail(ReactApplicationContext reactContext) {
        super(reactContext);
    }

    @Override
    public String getName() {
        return "SendEmail";
    }

    @ReactMethod
    public void sendEmail(final String emailAddress, final String subject) {
        Intent intent = new Intent(Intent.ACTION_SENDTO);
        intent.setData(Uri.parse("mailto:"));
        intent.putExtra(Intent.EXTRA_EMAIL  , new String[] { emailAddress });
        intent.putExtra(Intent.EXTRA_SUBJECT, subject);

        getCurrentActivity().startActivity(Intent.createChooser(intent, ""));
    }

    public static class ReactPackage implements com.facebook.react.ReactPackage {
        @Override
        public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
            return Collections.emptyList();
        }

        @Override
        public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
            List<NativeModule> modules = new ArrayList<>();
            modules.add(new NativeModuleSendEmail(reactContext));
            return modules;
        }
    }
}
```

Then register it:
```
return Arrays.<ReactPackage>asList(
          new NativeModuleSendEmail.ReactPackage()
    );
```

**Comment by roots-ai** [comment]
@ollydixon How to handle this for iOS?

**Comment by ollydixon** [comment]
@roots-ai I no longer do React Native. We have migrated onto Flutter.
