### ISSUE TITLE
rnpm link?

### ISSUE THREAD

**Issue by KjellConnelly** [chirag04/react-native-mail#61]
Just wondering if 
```
rnpm link
```
or
```
react-native link
```

works with this. I like that there are instructions for setting up on both platforms, but I really like it being done by typing in a single command more. If it does work, can you add this to the readme?

Also - readme might look better with es6 syntax

**Comment by geirman** [comment]
I've just verified that `react-native link` seems to work. 

Disclaimer: my app has built in both iOS and Android, but I've yet to successfully send an email. Still working on that. I get the error `not_available` when attempting to send mail, but if I dump `Mailer` I see the mail method attached to the object, so pretty confident the link worked and it's something else. I'm thinking this probably just doesn't work in emulators/simulators.

**Comment by chirag04** [comment]
@geirman not_available is probably because you are testing on a simulator which does not have the mail app configured.

Cloding this issue. feel free to send a PR if react-native link is not working.

**Comment by geirman** [comment]
Yes @chirag04, I didn't realize it wouldn't work on an emulator. I'll submit a PR to update the docs to mention that `react-native link` works now that I've successfully launched an email from my physical device. Would you also like me to update the example to use es6 syntax?

**Comment by chirag04** [comment]
@geirman sounds great. feel free to send a PR with those changes. 👍
