### ISSUE TITLE
UNMET PEER DEPENDENCY 

### ISSUE THREAD

**Issue by chatras** [chirag04/react-native-mail#63]
Hi guys,
Whenever I install the version 2.0.1 of this package, I get " UNMET PEER DEPENDENCY" error

npm i --save react-native-mail@2.0.1
```
├── UNMET PEER DEPENDENCY react-native@0.38.0
└── react-native-mail@2.0.1  
```

What does this error mean? Any idea what I am doing wrong? 

This is my rn version
```
react-native -v
react-native-cli: 1.2.0
react-native: 0.38.0
```

**Comment by chirag04** [comment]
rn-mail has no peer dep on rn. not sure what's going on with your setup.
