### ISSUE TITLE
Showing not_available in device

### ISSUE THREAD

**Issue by swaroopa94** [chirag04/react-native-mail#67]
Hi,
I am using this module when I click on email in my app then the mail  screen has to appear 
but here I am getting an error in console as  `not_available `

can anyone help  me to solve this

**Comment by chirag04** [comment]
if the email app is not configured on your device, it will show "not_available". You should check if email app is available or handle the error accordingly.

**Comment by swaroopa94** [comment]
Yes I had the gmail app in my device I tested it in iphone 6

**Comment by chirag04** [comment]
gmail app is not the default email app on iphone. it's the `mail` that is provided by ios.

**Comment by seamive** [comment]
What about Android Emulator? We're testing on Android Emulator with API 30 and still the same error @chirag04?
