### ISSUE TITLE
Implement `requiresMainQueueSetup`

### ISSUE THREAD

**Issue by simonemarinelli** [chirag04/react-native-mail#82]
react-native 0.49.2 generates a warning:

> Module RNMail requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by chirag04** [comment]
Happy to accept a PR

**Comment by simonemarinelli** [comment]
Pulled #83
