### ISSUE TITLE
Updating npm

### ISSUE THREAD

**Issue by Naoto-Ida** [chirag04/react-native-mail#86]
Could we possibly update the npm version?

There seems to be a recent commit on master that has fixed the error:
`RCTLog.js:48 Module RNMail requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

but it hasn't been tagged with `3.0.5` or whatever.

**Comment by chirag04** [comment]
done
