### ISSUE TITLE
Exception 'attachment must not be nil' iOS

### ISSUE THREAD

**Issue by 6axter82** [chirag04/react-native-mail#96]
Hi, I am getting the following error on iOS devices and in iOS simulator

![img_10b1065eda80-1](https://user-images.githubusercontent.com/13738101/35268761-58481cca-002a-11e8-99df-f9490b5b6584.jpeg)

Here is the piece of code I am using. It worked fine til recent. was there any version produced with any changes for attachments?

```
_handleEmail = () => {
	Mailer.mail({
		subject: '',
		recipients: ['feedback@mail.com'],
		ccRecipients: [''],
		bccRecipients: [''],
		body: '',
		isHTML: true,
		attachment: {
			path: '',  // The absolute path of the file from which to read data.
			type: '',   // Mime Type: jpg, png, doc, ppt, html, pdf
			name: '',   // Optional: Custom filename for attachment
		},
	}, (error, event) => {
		Alert.alert(
			error,
			event,
			[
			{text: 'Ok', onPress: () => console.log('OK: Email Error Response')},
					{text: 'Cancel', onPress: () => console.log('CANCEL: Email Error Response')}
			],
			{ cancelable: true }
		);
	});
}
```

Any ideas to solve this?

**Comment by iM-GeeKy** [comment]
If you do not need attachments simply comment that portion out, that should at least get you up and running. I believe the reason this is occurring is because another attribute is expected which is you haven't supplied therefor resulting in the error.

As for your simulator problem. You need to connect the mail app in simulator or else it will complain. Try running it directly on your device.

**Comment by chirag04** [comment]
Right. Closing as per the above explanation

**Comment by charlyBerthet** [comment]
I am getting the same error on my physical device (iOS) even though mail app is installed and I need to use `attachment`.

```
Mailer.mail({
              subject: `Report for ...`,
              recipients: ['email@domain.com'],
              ccRecipients: [],
              bccRecipients: [],
              body: '<b>Thanks for reporting, blablaba...</b>',
              isHTML: true,
              attachment: {
                path: filePath,
                type: 'txt',
                name: 'Report.txt',
              }
}, (error, event) => {
              console.log(error);
});
```

**Comment by charlyBerthet** [comment]
Ok figured our. Mime type should be 'text' and not 'txt'...

**Comment by charlyBerthet** [comment]
@chirag04 I have created a PR to correctly handle this error, it should be properly reported to Javascript layers: https://github.com/chirag04/react-native-mail/pull/141
